export enum ProjectStatus {
    PLAN_GENERATED = 'PLAN_GENERATED',
    PLAN_VALIDATED = 'PLAN_VALIDATED',
    PREVIEW_GENERATED = 'PREVIEW_GENERATED',
    GENERATING = 'GENERATING',
    COMPLETED = 'COMPLETED',
    PROJECT_CREATED = 'PROJECT_CREATED'
}