spring:
  # import du fichier qui contient les var d'env
  config:
    import: optional:file:.env[.properties]
  application:
    name: QuickExpo

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      idle-timeout: 300000
  debug: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/github"
            scope:
              - user:email
              - read:user
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true

  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: alpha
    tagsSorter: alpha
    filter: true
    tryItOutEnabled: true
    displayRequestDuration: true

  packages-to-scan: cm.mvtech._minexpo.controller
  paths-to-match: /api/**, /auth/**

  default-produces-media-type: application/json
  default-consumes-media-type: application/json

api:
  ai:
    hugging-face-key: ${HUGGINGFACE_KEY}
    hugging-face-model: deepseek-ai/DeepSeek-V3.2
    groq-key: ${GROQ_KEY_3}
    groq-model: ${GROQ_MODEL_2}
  url:
    frontend: ${FRONTEND_URL}
# jwt key
jwt:
  secret: ${JWT_SECRET_KEY}
  expiration-min: 86400000

logging:
  level:
    org.springframework.security: DEBUG
    org.springdoc: DEBUG
    org.springframework.web: DEBUG
    org.flywaydb: TRACE
server:
  port: 8080
